[package]
name = "netprobe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
default-net = "0.21"
xenet = "0.2"
hickory-resolver = "0.24"
tokio = "1.21"
futures = {version = "0.3", features = ["executor", "thread-pool"]}
